version: '3.8'

services:

  web:
    container_name: evcoordinator-web
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules