# #######
# Stage 1: Build Stage
FROM --platform=$BUILDPLATFORM node:23.8.0-bullseye-slim AS builder

ARG API_URL
ARG AUTH_AUTHORITY
ARG CLIENT_ID

RUN mkdir /project
WORKDIR /project

# Install Angular CLI and necessary dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci

# Copy and build the application
COPY . .
RUN sed -i "s|__API_URL__|${API_URL}|g" src/environments/environment.prod.ts
RUN sed -i "s|__AUTH_AUTHORITY__|${AUTH_AUTHORITY}|g" src/environments/environment.prod.ts
RUN sed -i "s|__CLIENT_ID__|${CLIENT_ID}|g" src/environments/environment.prod.ts
RUN cat -v src/environments/environment.prod.ts
RUN npm run buildProd

# #######
# Stage 2: Serve with nginx
FROM nginx:alpine
COPY --from=builder /project/dist /usr/share/nginx/html

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Replace existing nginx configuration to serve Angular files
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Entrypoint script to dynamically populate environment variables
ENTRYPOINT ["/entrypoint.sh"]
